### ISSUE TITLE
Programmer's Model of Sensors/Controls

### ISSUE THREAD

**Issue by lookfwd** [meltoner/agrofelis#1]
Is there a list with all the sensors and controllable elements the system has? Along with what protocols they use? This is what I reverse engineer from the manual:

| Qty | Region | Item | Description | Protocol |
| -- | -- | -- | -- | -- |
| 4 | Motors Hub WiFi Network  | SR250D motors | Wheels for Motors | On/Off with Gear Control|
| 2 | Motors Hub WiFi Network  | DS18B20 | Temperature Sensors | Onewire |
| 1 | Motors Hub WiFi Network  | Cooler Fan | Cooler Fan Control | On/Off |
| 4 | Motors Hub WiFi Network  | Current Sensors | Wheel Motor Current Sensor | 10 bit ADC/I2C |
| 4 | Mobility WiFi Network | Breaks controller |Breaks controller | On/Off |
| 4 | Mobility WiFi Network | Breaks Sensor | Breaks Sensor | Angular Encoding |
| 1 | Power Bluetooth | 4S 12V 250A SMART LIFEPO4 DELIGREEN BMS WITH BLUETOOTH BALANCING FUNCTION | Battery Management System | Bluetooth |
| 2 | Power Wifi Network | ESP8266 WiFi Relay |  Mains On/Off | WiFi |
| 2 | Mobility WiFi Network  | Linear Actuator | Steering Controller | On/Off |
| 2 | Mobility WiFi Network | Location Sensor | Location Feedback Sensor | 10 bit ADC |
| 1 | Lidar WiFi Network | MPU | MPU | I2C |
| 1 | Lidar WiFi Network | GPS | GPS | Serial |
| 1 | Lidar WiFi Network | Lidar | Lidar | Serial |
| 1 | Lidar WiFi Network | RDS3218 20KG 270 Degree Servo | Lidar angle control | Servo |
| 1 | Rim WiFi Network | Linear Actuator | Rim Angle | On/Off |
| 1 | Rim WiFi Network | Rim Rotation Motor| Rim Rotation | On/Off+Direction |
| 1 | All Networks | Remote Control | Remote Control with several Controls | WiFi |
| 1 | All Networks | Data Fusion | Data Fusion controller/logger + Vision | WiFi |

**Comment by meltoner** [comment]
very nice, extended it further to 

| Qty | Region/module | Connectivity | Item | Description | Protocol |
| -- | -- | -- | -- | -- | -- |
| 4 | Motors Hub | WiFi Network  | SR250D motors | Wheels for Motors | DAC controlling speed and e-brake (on 0 speed) |
| 4 | Motors Hub | WiFi Network | Relay | Controlling reverse or fwd  | Digital on/off|
| 4 | Motors Hub | WiFi Network | Relay | Controlling power | Digital on/off |
| 4 | Motors Hub | WiFi Network  | DS18B20 | Temperature Sensors | Onewire |
| 2 | Motors Hub | WiFi Network  | Cooler Fan | Cooler Fan Control | Always on |
| 4 | Motors Hub | WiFi Network  | Current Sensor | Wheel Motor Current Sensor | ADC esp32 |
| 4 | Motors Hub | WiFi Network  | Hall Sensors | Three for each wheel / odometer | 10 bit ADC/I2C |
| 1 | BMS | Serial | 8S 25V 250A SMART LIFEPO4 DELIGREEN BMS | Battery Management System | USB|
| 2 | Power | Wifi Network | ESP8266 WiFi Relay | Energizes front and back regions/Motor hubs | On/Off  |
| 2 | Steering | Serial  | Linear Actuator | Steering Controller | DAC speed (voltage) with reverse, two pwm via two DRV8871 |
| 2 | Steering | Serial / USB| Current Sensor | ADC on Arduino mega |
| 2 | Steering | Serial / USB| Location Sensor | Location Feedback Sensor | ADC Arduino mega |
| 2 | Braking | Serial  / USB | Breaks relay | Breaks  | On/Off (missing) |
| 4 | Braking | Serial  / USB| Breaks Servos | Breaks Sensor | PWM, Angular Encoding |
| 1 | Front Sensors Lidar | Serial / USB | mpu9250 |  9 degrees of freedom orientation | I2C |
| 1 | Front Sensors Lidar | Serial / USB | GPS | GPS | Serial |
| 1 | Front Sensors Lidar | Serial / USB | Lidar | Lidar | Serial |
| 1 | Front Sensors Lidar | Serial / USB | RDS3218 20KG 270 Degree Servo | Lidar angle control | PWM Angular Encoding |
| 1 | RIM | WiFi Network | Linear Actuator | Rim tilt | DAC/ speed (voltage) with reverse, two pwm via DRV8871 |
| 1 | RIM | WiFi Network | Stepper motor | Rim Rotation | Enable, Direction, speed/steps |
| 1 | RIM | WiFi Network | mpu9250 |  9 degrees of freedom orientation | I2C |
| 1 | All Networks | WiFi | Remote Control | Remote Control with several Controls | WiFi |
| 1 | Data Fusion | WiFi | Jetson nano | Data Fusion controller / logger + Vision| WiFi, USB hub |
| 1 | Data Fusion | WiFi | Data processing | Coral | NN accelerator | USB 3 |

**Comment by lookfwd** [comment]
* The "mpu9250 - 9 degrees of freedom orientation" is a different approach to the resistor-based "Location Sensor" that you've used with the Steering Controller Linear Actuator.
* The three hall sensors - I guess are something like [this](https://www.amazon.com/SaiDian-2-Wheels-Electric-Vehicles-Element/dp/B0BQ6MK4LY/). I guess [this](https://github.com/meltoner/agrofelis/blob/ecad0c5d07a8ae1df6f086fa8f3dcd3df8286816/components/mobility/motors_hub_driver/src/DualMotorDriverFront/SensorHalls.h#L37) is a way to convert it to some form of [gray code](https://electronics.stackexchange.com/posts/15482/revisions).

**Comment by lookfwd** [comment]
On the three hall sensors, you mean that the weel had an internal control system that isn't trustworthy and there's a need to intercept the wheel's sensors and double-control the drive of the wheel? Or it's something else - like the wheel doesn't implement the control function you want and you need to modify it by double-controlling? Or the wheel has the sensors but it doesn't use them for control but only provides them externally for others to control the drive voltage?

**Comment by meltoner** [comment]
Yes but its not about trustworthiness, its different concerns. 
If i don't intercept it then i do not know it. if i don't know it then i am blind, i can't know if the wheels moved or not. Their internal system must be for another reason than mine. I suppose theirs is for interchanging the coils polarity accordingly for a given speed. 

Imagine you are in a motorcycle and you are on a flat ground, you need 20% of the throttle, then you meet a small hill, you need 50% of the throttle, then you are in a decline you need 0% of the throttle. The keep a constant end speed is my requirement not of their drivers. These drivers are made so a human operates them using a throttle,  and by intercepting the hall sensors I am able to replace the human operator with an esp32. 

Its analogues with an actual motorbike with an internal combustion engine, they have a system that they control the "explosions" synchronicity, but that is irrelevant with how much throttle the driver applies to overcome the ground resistance depending on the slope.

**Comment by lookfwd** [comment]
## The KT36 controller and Hall Sensors

> Their internal system must be for another reason than mine

Pretty interesting. There's almost no data on it. [This](http://www.suringmax.com/index.php?m=home&c=View&a=index&aid=139) is the controller. Here are two pdfs [1](https://cdn.shopifycdn.net/s/files/1/0040/9223/1778/files/9-18MOSFET_Controller_Connection_Manual-ConhisMotor.pdf?v=1599719229), [2](https://cdn.shopifycdn.net/s/files/1/0040/9223/1778/files/KTController_FAQ.pdf?v=1596527413) that seem to talk about pretty much the same controller. They seem to suggest that it's used for controlling something, as wiring them differently, will result on the wheel turning the wrong way.

Bottom line, likely they are used by the controller, but they could potentially just be used to drive the display and not the controller. I don't know.

## The Real Problem

I think the main problem isn't that you are driving blind. You are driving blind with the hall sensors too, since the fact that wheels rotate, doesn't mean that they touch the ground. They might be spinning - somethingABS is supposed to mitigate. The main problem is the fact that you have to synchronize 4 such controllers and you want to avoid "skid steering" [3](https://www.prorobot.ru/load/kniga_C069.pdf), [4](https://www.ri.cmu.edu/pub_files/pub1/shamah_benjamin_1999_1/shamah_benjamin_1999_1.pdf) since you have a more effective way of steering. So you need to implement a 4WD (or AWD) differential with software, which... well... I can't find anyone who has successfully done this.

[Differentials](https://youtu.be/nC6fsNXdcMQ?si=G14BuGZTdpjOeVKT) are more than 100 years old and they work and they are cheap and all. With differentials, [the wheel who gives the least resistance gets more energy](https://www.quora.com/How-does-the-differential-system-actually-know-which-wheel-to-power-more-what-is-its-feedback-system). That's a physical property of the system, and there's no real control mechanism.

How do you implement that in software?

Here's [a guy who tried to do this](https://www.youtube.com/watch?v=ET1HEyqEQJQ). No controller/feedback as far as I can say. Just manual coefficients and funny behavior. [Another guy](https://youtu.be/pDQtSdQI98o?si=Vx0iMgIC8K24SV78) started and stopped at part.3 with no conclusion. Both those guys seem to have accidentally got in that rabbit hole and regretted it.

Some other guy commented that this is also called "Torque Vectoring" [5](https://youtu.be/bD2Do1gAuog?si=QHeWvS8rWdjnQWxN), [6](https://www.carexpert.com.au/car-news/torque-vectoring-explained). And it seems like exactly what is needed here.

But I feel it's so much out of scope. That's research. And nobody is really using it out there. Just R&D. There should be some thought about how did the vehicle got this problem. Is it an essential problem that needs to be solved? Can one solve just this one problem well and become multi-millionaire, without having anything to do with robots and agriculture?

## What Current Software Does

I can see that the sensor defines something called `position` in units related to the angle of the wheel defined by one pass in front of the sensor. Based on that the control logic is [here](https://github.com/meltoner/agrofelis/blob/ecad0c5d07a8ae1df6f086fa8f3dcd3df8286816/components/mobility/motors_hub_driver/src/DualMotorDriverBack/Motor.cpp#L152C50-L152C50). The `targetPosition` is set relatively to the current position [here](https://github.com/meltoner/agrofelis/blob/ecad0c5d07a8ae1df6f086fa8f3dcd3df8286816/components/mobility/motors_hub_driver/src/DualMotorDriverBack/Motor.cpp#L131) since `hallsSensor.position = 0` in the same function. In this way errors don't accumulate.

Both motors in front (or back) are set to the same target position:

```
motorA.moveToPosition(commandInt);
motorB.moveToPosition(commandInt);
```

There are alternative commands that set the speed values for individual motors. There's also [a method that synchronizes the two speeds](https://github.com/meltoner/agrofelis/blob/ecad0c5d07a8ae1df6f086fa8f3dcd3df8286816/components/mobility/motors_hub_driver/src/DualMotorDriverFront/MotorsHubController.cpp#L84C3-L84C24) using the sensor calculations, when `setSpeed()` or `setPower()` are used.

**Comment by meltoner** [comment]
Very nice resources. 
We can detect if the wheel is rotating freely, if the rotations over exceed the other wheels, or because current is low, (this also is taken into account). A form of suspension would also render the free wheel rotation, case non existence more or less. 

Differentials are applicable but consume a lot of space and are to be employed on larger models where a motor hub can't be employed. 
Although it sounds like a big deal and one could attempt to calculate and apply the ideal signals, which we also pursuit, in practice none of this is actually necessary!

The key reason why nothing specially has to be employed is because the wheels wont resist if someone helps them move faster in the same direction as their indicated speed. This effectively is what a differential mechanism is, i.e. one wheel will move freely while turning. Having said that, if one was predicting the forces of the ground while turning, one could drive each wheel such that they move to match these, and as such distribute the forces exactly as needed, and no motor would shortly have to work for both motors from the pair. 

The current software, implemented the following behaviors.
Each wheel independently looks to find the right voltage such that the desired speed is matched. On top of that their coordinator, observes their speed difference between the left and the right pair/module and attempts to minimize it. 

So at the end we can ask both modules to move at X speed and all of them will adapt, either by the feedback information, either by the physical environment, either because even if we haven't done something special, it would still work. 

Because we have the feedback sensors / and data in place, as a "platform", we can implement the ideal, or let the system find it in the future. The system moreover, records all this info. The big guyz in the car industry have a similar though harder problem, because of the speeds involved, ice, etc, but yes its analogous.

**Comment by lookfwd** [comment]
Awesome. Makes sense.
